name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - name: Run unit tests
        run: uv run --python ${{ matrix.python-version }} --extra test pytest

  test-protobuf-compat:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Builds to validate alternate versions of protobuf 
          - python-version: "3.9"
            protobuf-version: ">=3.19.0,<3.20"
          - python-version: "3.9"
            protobuf-version: ">=3.20.0,<3.21"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - name: Run unit tests (protobuf ${{ matrix.protobuf-version }})
        run: uv run --python ${{ matrix.python-version }} --extra test --with 'protobuf${{ matrix.protobuf-version }}' pytest
